### ISSUE TITLE
Invalid recoverable key

### ISSUE THREAD

**Issue by SimoneAcca** [commercionetwork/sacco.cs#4]
I was trying the shareDocument example with that configuration:
```
var res = await commercio.sdk.DocsHelper.shareDocument(
                id: docId,
                contentUri: "https://example.com/document",
                metadata: new commercio.sdk.CommercioDocMetadata(
                    contentUri: "https://example.com/document/metadata",
                    schema: new commercio.sdk.CommercioDocMetadataSchema(
                        uri: "https://example.com/custom/metadata/schema",
                        version: "1.2.3"
                    ),
                    schemaType: "xml"
                ),
                recipients: docRecipientDid,
                fees: fees,
                wallet: wallet,
                aesKey: null,
                checksum: new CommercioDocChecksum(
                    "ed076287532e86365e841e92bfc50d8c",
                    CommercioDocChecksumAlgorithm.MD5
                ),
                encryptedData: null
            );
```
but I obtain the following error:
```
Unhandled exception. System.ArgumentException: Invalid recoverable key!
   at commercio.sacco.lib.TransactionSigner.deriveFrom(Byte[] message, ECPrivateKeyParameters privateKey, ECPublicKeyParameters publicKey) in ...\sacco.cs\sacco\Code\utils\TransactionSigner.cs:line 84
   at commercio.sacco.lib.Wallet.signTxData(Byte[] data) in ...\sacco.cs\sacco\Code\Wallet.cs:line 240
   at commercio.sacco.lib.TxSigner._getStdSignature(Wallet wallet, AccountData accountData, NodeInfo nodeInfo, List`1 messages, StdFee fee, String memo) in ...\sacco.cs\sacco\Code\TxSigner.cs:line 90
   at commercio.sacco.lib.TxSigner.signStdTx(Wallet wallet, StdTx stdTx) in ...\sacco.cs\sacco\Code\TxSigner.cs:line 50
   at commercio.sdk.TxHelper.createSignAndSendTx(List`1 msgs, Wallet wallet, StdFee fee) in ...\commercio-sdk.cs\sdk\Code\tx\TxHelper.cs:line 37
   at commercio.sdk.DocsHelper.shareDocument(String id, String contentUri, CommercioDocMetadata metadata, List`1 recipients, List`1 fees, Wallet wallet, CommercioDocChecksum checksum, KeyParameter aesKey, List`1 encryptedData) in ...\commercio-sdk.cs\sdk\Code\docs\DocsHelper.cs:line 93
   at BlockChainTest.Program.Main(String[] args) in ...\Program.cs:line 28
   at BlockChainTest.Program.<Main>(String[] args)
```

**Comment by ErichUdet** [comment]
The invalid recoverable key exception has been corrected.
